### ISSUE TITLE
Firefox: Cross-site POST form submissions are forbidden

### ISSUE THREAD

**Issue by mstelbrink** [whosFritz/Portfolio-SvelteKit#16]
When clicking on the "Akzeptieren" button (cookie banner) in Firefox 115.12.0esr (64-Bit) the following error message appears in a new browser tab:

![grafik](https://github.com/user-attachments/assets/7dbfff34-a15c-4c87-8526-e7d3162d4537)

It was also tested on Chromium 126.0.6478.126 without any issue.

**Comment by whosFritz** [comment]
Still happening with fire fox?

**Comment by whosFritz** [comment]
Fixed by [Commit fixing csrf](https://github.com/whosFritz/Portfolio-SvelteKit/commit/7d956c37049944cce1b527289bf4d560a6d30978)

Problem caused by sveltkit making difference between www.whosfritz.de and whosfritz.de and ORIGIN env variable isn't working for both
